// Auto-generated by scripts/sync-scenes.ts — do not edit manually
// Run: bun scripts/sync-scenes.ts
import './aurora-scene';
import './dna-scene';
import './fractal-scene';
import './galaxy-scene';
import './geometric-scene';
import './kaleidoscope-scene';
import './lava-scene';
import './matrix-scene';
import './metaballs-scene';
import './nebula-scene';
import './ocean-scene';
import './orb-scene';
import './particle-scene';
import './rings-scene';
import './starburst-classic-scene';
import './starburst-flat-scene';
import './starburst-scene';
import './starburst-sharp-scene';
import './starburst-soft-scene';
import './starburst-spin-scene';
import './starfield-scene';
import './terrain-scene';
import './tunnel-scene';
import './voronoi-scene';
import './vortex-scene';
import './waveform-scene';

export {
  createScene,
  getAvailableScenes,
  getSceneMetadata,
  getAllSceneMetadata,
} from './scene-registry';
export type { SceneHandler, SceneParamDef, SceneRegistration } from './types';
