#!/usr/bin/env bun
/**
 * Auto-generates the scenes barrel (scenes/index.ts) from scene files on disk.
 * Run: bun scripts/sync-scenes.ts
 * Also runs automatically before dev/build via package.json scripts.
 */
import { readdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const SCENES_DIR = join(import.meta.dirname, '../src/components/visualizer/scenes');
const BARREL_PATH = join(SCENES_DIR, 'index.ts');

const sceneFiles = readdirSync(SCENES_DIR)
  .filter((f) => f.endsWith('-scene.ts') && f !== 'index.ts')
  .sort();

const imports = sceneFiles.map((f) => `import './${f.replace('.ts', '')}';`).join('\n');

const barrel = `// Auto-generated by scripts/sync-scenes.ts — do not edit manually
// Run: bun scripts/sync-scenes.ts
${imports}

export {
  createScene,
  getAvailableScenes,
  getSceneMetadata,
  getAllSceneMetadata,
} from './scene-registry';
export type { SceneHandler, SceneParamDef, SceneRegistration } from './types';
`;

writeFileSync(BARREL_PATH, barrel);

const count = sceneFiles.length;
console.log(`Synced ${count} scene${count === 1 ? '' : 's'} → scenes/index.ts`);
